### ISSUE TITLE
About the parameter asppold

### ISSUE THREAD

**Issue by Sam1224** [Xiangyi1996/PPNet-PyTorch#14]
Hi,

Thanks for your great work!
May I ask what's the parameter `asppold` for? I could find this parameter in your logs related to +Par+Sem, but cannot find it in my run (I think this parameter may be important, as PANet* appears to be normal, but +Par+Sem has a very low score).
![image](https://user-images.githubusercontent.com/33482912/155257028-0ce822f8-be42-4bef-a195-5589d3733dc7.png)

**Comment by youngfly11** [comment]
Thanks for your attention.
Hi @Xiangyi1996, could you please take a look at this issue? Thanks.

**Comment by Xiangyi1996** [comment]
Hi, this parameter means nothing but an aspp atrous rate. "old" means we use the [6,12,18,24] the same as current code. 
I reproduced every experiment and provide the logs 2 years ago. Any parameter could be changed is fixed in the training scripts.
Maybe you could check your pytorch version and each parameters in the script. I am sure each result could be reproduced.

**Comment by Sam1224** [comment]
> Hi, this parameter means nothing but an aspp atrous rate. "old" means we use the [6,12,18,24] the same as current code. I reproduced every experiment and provide the logs 2 years ago. Any parameter could be changed is fixed in the training scripts. Maybe you could check your pytorch version and each parameters in the script. I am sure each result could be reproduced.

Thanks for your reply! I will have a check.
